/* ── Putting two hourly series on one grid ───────────────────────────────────

   `BlocksProducedSeries` (`explorer.ts`) and `RewardSeries` (`rewards.ts`) are
   both 24 rolling hourly buckets, but each is cut from the chain head as of
   *its own* fetch: two `unstable_cache` entries with independent 5-minute TTLs,
   regenerated by whichever request happened to find one stale. Their grids
   therefore sit minutes apart, and nothing keeps that below a bucket edge —
   a payout logged 21:58 lands in the reward bucket opening 21:03 but in the
   blocks bucket opening 21:07's *predecessor*, and the overlay draws it one
   hour away from the blocks that earned it.

   Overlaying by array index assumes the grids agree. This module makes that
   assumption true by re-indexing one series onto the other's grid.
   ────────────────────────────────────────────────────────────────────────── */

const HOUR_MS = 3_600_000;

/** The slice of an hourly series this module needs — satisfied as-is by both
    `BlocksProducedSeries` (via `counts`) and `RewardSeries`. */
export type HourlyGrid = {
  /** One total per bucket, oldest first. */
  values: number[];
  /** Unix-ms start of each bucket, aligned 1:1 with `values`. */
  bucketStarts: number[];
};

export type AlignedPair = {
  /** `a`'s values over the shared window. */
  a: number[];
  /** `b`'s values for the *same hours*, so index i of both is one hour. */
  b: number[];
  /** Bucket starts of the shared window, taken from `a` — the series whose
      grid the pair is expressed in, and so the one the axis labels read. */
  bucketStarts: number[];
  /** How many buckets `b`'s grid sat ahead of `a`'s (negative = behind). 0 in
      the ordinary case where both caches were filled inside the same hour. */
  shift: number;
};

/**
 * Line two hourly series up by wall-clock time rather than by array index, and
 * return only the hours both actually cover.
 *
 * The offset is rounded to a whole bucket and the values are moved, never
 * split: a bucket holds a *total* for its hour, so smearing it proportionally
 * across two buckets would invent fractional blocks and fractional payouts that
 * no source ever reported. Rounding leaves at most half an hour of skew between
 * the two grids — the closest two independently-cut grids can come without
 * re-bucketing the raw data, which neither cache keeps.
 *
 * Returns null when the windows no longer overlap at all (both caches would
 * have to be a full day apart), so the caller can say so instead of drawing a
 * comparison out of nothing.
 */
export function alignHourly(a: HourlyGrid, b: HourlyGrid): AlignedPair | null {
  if (a.values.length === 0 || b.values.length === 0) return null;

  // b's index j holds the same hour as a's index j + shift.
  const shift = Math.round((b.bucketStarts[0] - a.bucketStarts[0]) / HOUR_MS);
  const lo = Math.max(0, shift);
  const hi = Math.min(a.values.length - 1, b.values.length - 1 + shift);
  if (hi < lo) return null;

  const out: AlignedPair = { a: [], b: [], bucketStarts: [], shift };
  for (let i = lo; i <= hi; i++) {
    out.a.push(a.values[i]);
    out.b.push(b.values[i - shift]);
    out.bucketStarts.push(a.bucketStarts[i]);
  }
  return out;
}
